name: Deploy Vite React App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SECRET_KEY }}

      - name: Deploy to EC2 server
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@13.127.116.15 << 'EOF'
            # Ensure Node.js, pm2, and serve are installed
            curl -fsSL https://rpm.nodesource.com/setup_20.x | sudo bash -
            sudo yum install -y nodejs
            sudo npm install -g pm2 serve

            # Navigate to the project directory
            if [ -d "React-Notes-app" ]; then
              cd React-Notes-app
              git pull origin main
            else
              git clone https://github.com/HarshAgrawalSB/React-Notes-app.git
              cd React-Notes-app
            fi

            # Install dependencies and build the project
            npm install
            npm run build

            # Kill any existing processes on port 5173 (or other ports if needed)
            lsof -t -i:5173 | xargs kill -9 || true
            lsof -t -i:5174 | xargs kill -9 || true
            lsof -t -i:5175 | xargs kill -9 || true

            # Serve the built files using pm2
            pm2 start node_modules/.bin/serve --name "react-notes" -- -s dist -p 5173

            # Save the pm2 process list and configure it to restart on reboot
            pm2 save
            pm2 startup

            # Exit the SSH session
            exit
          EOF
